### ISSUE TITLE
Code for extracting the features is not found

### ISSUE THREAD

**Issue by qingchenwuhou** [ruotianluo/Image_Captioning_AI_Challenger#2]
Hi, ruotian:
  The code path of bottom-up feature extracting can't be found. 
  Is there something wrong with it?
  Many thanks for restoring it.

**Comment by ruotianluo** [comment]
That's currently a placeholder.  You can try modifying the tools/generate_tsv.py in original repository by yourself. It should be trivial. I would suggest find some way to download the features because it takes days to extract the features on a single 1080ti

**Comment by qingchenwuhou** [comment]
ok, thanks!
