### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by AdamTTong** [ruotianluo/Image_Captioning_AI_Challenger#3]
what is the represention in chinese_bu_fc，chinese_bu_att and chinese_bu_box？
how many boxes you use?
can  you give me the code of  extracting  feature?

**Comment by ruotianluo** [comment]
bottom-up-attention-ai-challenger

**Comment by ruotianluo** [comment]
https://github.com/ruotianluo/bottom-up-attention-ai-challenger
run tools/generate_tsv.py. (need to change paths in the file.)
