### ISSUE TITLE
The width and the height of the images

### ISSUE THREAD

**Issue by curry24** [ruotianluo/Image_Captioning_AI_Challenger#5]
Hi, ruotian, thanks a lot for your code. But I have a problem. I find there are some images which have information in json file but don't exist in the image folder. In this case, how do you process the width and the height of these images?

**Comment by ruotianluo** [comment]
I don't have this problem.

**Comment by curry24** [comment]
But I encounter an error like this when run the script prepro_labels.py :
File "scripts/prepro_labels.py", line 176, in main
    with Image.open(os.path.join(params['images_root'], img['filepath'], img['filename'])) as _img:
File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2477, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'data/ai_challenger/caption_train_images_20170902/6f8605598c489d00a10221630da60c8dd936d4e1.jpg'
Maybe the image folder I downloaded miss some images. Thank you a lot!
